server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: userdb
    password: changemeinprod!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://lakshaycd:lakshay@localhost:8761/eureka/

security:
  jwt:
    secret-key: bde05efd186b5f1504be2a8213cebf54
    expiration-time: 3600000